USE [master]
GO

/****** Object:  Database [gayflix2_db]    Script Date: 2019-11-04 12:21:24 ******/
CREATE DATABASE [gayflix2_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'gayflix', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\gayflix.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'gayflix_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\gayflix_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [gayflix2_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [gayflix2_db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [gayflix2_db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [gayflix2_db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [gayflix2_db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [gayflix2_db] SET ARITHABORT OFF 
GO

ALTER DATABASE [gayflix2_db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [gayflix2_db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [gayflix2_db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [gayflix2_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [gayflix2_db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [gayflix2_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [gayflix2_db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [gayflix2_db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [gayflix2_db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [gayflix2_db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [gayflix2_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [gayflix2_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [gayflix2_db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [gayflix2_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [gayflix2_db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [gayflix2_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [gayflix2_db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [gayflix2_db] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [gayflix2_db] SET  MULTI_USER 
GO

ALTER DATABASE [gayflix2_db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [gayflix2_db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [gayflix2_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [gayflix2_db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [gayflix2_db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [gayflix2_db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [gayflix2_db] SET  READ_WRITE 
GO

