//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gayflix3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gayflix2_dbEntities : DbContext
    {
        public gayflix2_dbEntities()
            : base("name=gayflix2_dbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> booking { get; set; }
        public virtual DbSet<cinema> cinema { get; set; }
        public virtual DbSet<lounge> lounge { get; set; }
        public virtual DbSet<seat> seat { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<viewing> viewing { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
