//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gayflix3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int id { get; set; }
        public int bookingid { get; set; }
        public int seatid { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual seat seat { get; set; }
    }
}
